// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UbicatApi.Models;

#nullable disable

namespace ubicatapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260107105230_FechaUltimoEscaneoQR")]
    partial class FechaUltimoEscaneoQR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UbicatApi.Models.Categorias", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCategoria"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombreCategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idCategoria");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.Comentarios", b =>
                {
                    b.Property<int>("idComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idComentario"));

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idForo")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idComentario");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.Foro", b =>
                {
                    b.Property<int>("idForo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idForo"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fechaPublicacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("imagenPrincipal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idForo");

                    b.ToTable("foro", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.FotosForo", b =>
                {
                    b.Property<int>("idFotos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idFotos"));

                    b.Property<int>("idForo")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("urlFoto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idFotos");

                    b.ToTable("fotosforo", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.Mascota", b =>
                {
                    b.Property<int>("idMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idMascota"));

                    b.Property<string>("cuidados")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("enfermedades")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("especie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("foto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idMascota");

                    b.HasIndex("idUsuario");

                    b.ToTable("mascota", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.QR", b =>
                {
                    b.Property<int>("idQR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idQR"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fechaGeneracion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fechaUltimoEscaneo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idMascota")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ubicacionActual")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("urlDatosMascota")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idQR");

                    b.HasIndex("idMascota")
                        .IsUnique();

                    b.ToTable("qr", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.ReporteMascota", b =>
                {
                    b.Property<int>("idReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idReporte"));

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("foto")
                        .HasColumnType("longtext");

                    b.Property<int>("idMascota")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuarioReporta")
                        .HasColumnType("int");

                    b.Property<string>("mensaje")
                        .HasColumnType("longtext");

                    b.Property<string>("tipoReporte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ubicacion")
                        .HasColumnType("longtext");

                    b.HasKey("idReporte");

                    b.HasIndex("idMascota");

                    b.ToTable("reporte_mascota", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("clasificacionPromedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("especialidad")
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idUsuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.Validaciones", b =>
                {
                    b.Property<int>("idValidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idValidacion"));

                    b.Property<int>("idComentario")
                        .HasColumnType("int");

                    b.Property<int>("idUsuarioValidador")
                        .HasColumnType("int");

                    b.Property<string>("observacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("puntuacion")
                        .HasColumnType("int");

                    b.HasKey("idValidacion");

                    b.ToTable("validaciones", (string)null);
                });

            modelBuilder.Entity("UbicatApi.Models.Mascota", b =>
                {
                    b.HasOne("UbicatApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UbicatApi.Models.QR", b =>
                {
                    b.HasOne("UbicatApi.Models.Mascota", "Mascota")
                        .WithOne("QR")
                        .HasForeignKey("UbicatApi.Models.QR", "idMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("UbicatApi.Models.ReporteMascota", b =>
                {
                    b.HasOne("UbicatApi.Models.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("idMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("UbicatApi.Models.Mascota", b =>
                {
                    b.Navigation("QR")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
